# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Skillmap < Formula
  desc "Capability differ for AI agent skills"
  homepage "https://github.com/TakasiVenkataSandeep-08/agentskillmap"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.0/skillmap-darwin-arm64.tar.gz"
      sha256 "347d9e4dfb047996da30f25d08dd9adcc6fa236ac693f1684c9eda0d7e8cc6f4"
    end
    on_intel do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.0/skillmap-darwin-x64.tar.gz"
      sha256 "bccf2a9a52de9e102813410f73c7932e127fd73144091802282c9caa6cc4f14a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.0/skillmap-linux-arm64.tar.gz"
      sha256 "4cbb90e95a9d30d0847c5353282592769540d909a687ad84c8a70395189f5348"
    end
    on_intel do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.0/skillmap-linux-x64.tar.gz"
      sha256 "4e6d101f7b34ee0388b5071e7caaee20a95ac3da3f863a9f3d03e62bc2fa90e8"
    end
  end

  def install
    bin.install "skillmap"
  end

  test do
    # Not a version banner. The binary carries its own rules, and a build that
    # embedded none would scan every project clean — so the test asserts it can
    # actually detect something.
    assert_match "skillmap #{version}", shell_output("#{bin}/skillmap version")
    assert_match "credential-read", shell_output("#{bin}/skillmap rules")
  end
end
