# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Skillmap < Formula
  desc "Capability differ for AI agent skills"
  homepage "https://github.com/TakasiVenkataSandeep-08/agentskillmap"
  version "0.5.5"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.5/skillmap-darwin-arm64.tar.gz"
      sha256 "f04c81272cc7d5f29bdc4e0b49e3ce7eae0686ee9065757b128d1072bedd13f3"
    end
    on_intel do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.5/skillmap-darwin-x64.tar.gz"
      sha256 "d3cf1e6553d956b7e54658c475bd949c67f965e1ba42c5d219fee9037634987f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.5/skillmap-linux-arm64.tar.gz"
      sha256 "a2541cdcbc833a80a99a1f6bb4f57024048aa305702b8b4526fde44c3286785b"
    end
    on_intel do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.5/skillmap-linux-x64.tar.gz"
      sha256 "60f9f926f26af0ae8db14d982fbdacc8ed04c01d43f540c85ef1236cc83b2a27"
    end
  end

  def install
    bin.install "skillmap"
  end

  test do
    # Not a version banner. The binary carries its own rules, and a build that
    # embedded none would scan every project clean — so the test asserts it can
    # actually detect something.
    assert_match "skillmap #{version}", shell_output("#{bin}/skillmap version")
    assert_match "credential-read", shell_output("#{bin}/skillmap rules")
  end
end
