# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Skillmap < Formula
  desc "Capability differ for AI agent skills"
  homepage "https://github.com/TakasiVenkataSandeep-08/agentskillmap"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.3/skillmap-darwin-arm64.tar.gz"
      sha256 "6741d4d99d41ebe045fed8aba20fdab6b7ace5a05e3ff6d7f7f588a363ec014a"
    end
    on_intel do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.3/skillmap-darwin-x64.tar.gz"
      sha256 "8a5025f6d625cc3f51dcbf34b1b85701b97b50ae8919705cc32416e9aab519b8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.3/skillmap-linux-arm64.tar.gz"
      sha256 "ba445578ea39edd3bfa87ded3bec3b7e4e0ad9dd3337570fb5c600bf24438072"
    end
    on_intel do
      url "https://github.com/TakasiVenkataSandeep-08/agentskillmap/releases/download/v0.5.3/skillmap-linux-x64.tar.gz"
      sha256 "5229be4b7696bb58e187dea6408b8cda1e76223ada9190897b1d39a734afd69d"
    end
  end

  def install
    bin.install "skillmap"
  end

  test do
    # Not a version banner. The binary carries its own rules, and a build that
    # embedded none would scan every project clean — so the test asserts it can
    # actually detect something.
    assert_match "skillmap #{version}", shell_output("#{bin}/skillmap version")
    assert_match "credential-read", shell_output("#{bin}/skillmap rules")
  end
end
